### PR TITLE
Atom-mp4 PR with minor changes

### PR DESCRIPTION
**Pull request by S-PScripts**
Atom-mp4 PR with minor changes

### CODE REVIEW

**Comment by fuckusfm** [comment]
i dont see why fakekick, fakeban would be here. pretty much useless.

**Comment by S-PScripts** [comment]
yeah i thought so too. but i didn't really make this

**Comment by fuckusfm** [comment]
you can remove blackesp, fakekick, fakeban
and i will merge it

**Comment by S-PScripts** [comment]
I've deleted those commands now.
also you can close the other pull request since this one is just that with some small edits

**Pull request merged**
